### ISSUE TITLE
[Feature request] Relative OSD position

### ISSUE THREAD

**Issue by Kristinita** [marius-sucan/KeyPress-OSD#1]
### 1. Request

It would be nice, if you add an option — relative OSD position.

For example, it would be nice, if would be possible position OSD in center and bottom of current window.

This was implemented in @tmplinshi KeyPress OSD version.

### 2. Expected behavior

Demonstration of tmplinshi version:

![Demo](https://imgur.com/KJnZ7nO.png)

### 3. Argumentation

I record screencasts with OSD.

#### 3.1. Center position

It would be nice, if OSD would be located in the center. Screencasts of the screen will be more beautiful.

![Center](https://i.imgur.com/Y8K6565.png)

In your KeyPress OSD version I don't know, how I can place OSD in the center.

#### 3.2. Different programs

Different programs have different GUI size and different GUI position on the screen.

**If** I use your KeyPress OSD version:

    I need to change OSD position each time.

**Elif** I use tmplinshi version:

    I don't need manually set OSD position.

### 4. Not helped

`Preferences` → `OSD appearences` → I don't find, how I can get expected behavior.

Thanks.

**Comment by marius-sucan** [comment]
You can enable "Allow easy OSD repositioning on click" at Preferences > OSD appearances. Have you tried it? The differences in DPI across screens/PCs prevented me from implementing what Tmplinshi did.

You cannot have it align to center. But I might add this option.

**Comment by marius-sucan** [comment]
I implemented centered alignment, Kris.

**Comment by Kristinita** [comment]
@marius-sucan, I'm sorry, tmplinshi version have another behavior:

![Tmplinshi version](https://i.imgur.com/scCrBeR.png)

Keys display in center of active window.

+ If window resize, keys display in center of resized window.
+ If new window is active, keys display in center of new active window.

Thanks.

**Comment by marius-sucan** [comment]
I will not implement this feature. Sorry.

**Comment by marius-sucan** [comment]
For you, I implemented Centered alignment.
