### ISSUE TITLE
Download of repo blocked due to threat detected by virus checkers (Generik.NESNPKT)

### ISSUE THREAD

**Issue by lconover** [marius-sucan/KeyPress-OSD#10]
Just as a heads-up, the following is being detected by multiple virus checkers as a potential Trojan in your .zip archive:  Generik.NESNPKT    You may want to doublecheck your system for potential issues and verify that your commercially available build does not have this same issue.  

The warning logged by one checker was as follows:
> HTTP filter;file;https://raw.githubusercontent.com/marius-sucan/KeyPress- OSD/master/keypress-osd-compiled.zip;a variant of Generik.NESNPKT trojan;connection terminated;{removed)\(removed);Event occurred during an attempt to access the web by the application: C:\Program Files (x86)\Google\Chrome\Application\chrome.exe  

This particular issue set off both ESET NOD32 and Sophos checkers so it may not be entirely a false alert.

**Comment by marius-sucan** [comment]
Hello!

Yes, Antivirus software usually marks AHK compiled scripts as viruses....

It is not a problem specific to KeyPress OSD . Read about it, it is common for AHK.

Best regards, Marius.
