### ISSUE TITLE
Underlining the selected text wouldn't be better? Instead of inserting that lola2 character. 

### ISSUE THREAD

**Issue by vassilyzaitsev** [marius-sucan/KeyPress-OSD#12]
I think it would look better...

I fell like you can't do that with ahk using "Gui, font"... Underlining part of the text inside a control. 

But, I was thinking that a converter like this: https://yaytext.com/underline/ could do the work, though...

Just a thought.

**Comment by vassilyzaitsev** [comment]
I was doing some testing: https://i.imgur.com/bP6OROq.png

And tbh it doesn't look as clean and "better" as I thought it would.

I don't know if it's worth it.. 😅

**Comment by marius-sucan** [comment]
Hello!

Thank you for trying to implement that. As far as I can tell, that would work only with specific fonts, not any font...

Lola and Lola2 were specifically chosen to be sufficiently common in various fonts.

The latest version of KeyPress OSD , has support for something else. It highlights the selected text with a semi-transparent window on top of it. Please try the commercial edition to see how it behaves. I also use a zero width caret.

Best regards, Marius.
