### ISSUE TITLE
Error: Call to non existence

### ISSUE THREAD

**Issue by ThePresence** [marius-sucan/KeyPress-OSD#13]
Hi,

I'm getting below error.

![image](https://user-images.githubusercontent.com/19200271/86516124-b824f880-be3b-11ea-933d-8e030b4f70b5.png)

**Comment by marius-sucan** [comment]
You are not running the correct AHK_H version.

Please use AHK_H v1 to run the script.

https://hotkeyit.github.io/v2/

Best regards, Marius.
