### ISSUE TITLE
Unsupported: Microsoft 옛한글 [KO] 한국어. 00000412 044120412

### ISSUE THREAD

**Issue by nanpuhaha** [marius-sucan/KeyPress-OSD#14]
Please support Korean language.

![Unsupported](https://user-images.githubusercontent.com/9074297/87238121-6ed73900-c439-11ea-8c06-449c2989aca4.jpg)

**Comment by marius-sucan** [comment]
In «alternate tyyping mode» , it should be supported, in the latest KeyPress OSD version, commercial edition.

Best regards, Marius.
