### ISSUE TITLE
Disabling "Do not show Left Click, PrintScreen..." prevents the capture of double click events

### ISSUE THREAD

**Issue by chrislockwood** [marius-sucan/KeyPress-OSD#15]
This frustrates the creation of software walk-through guides which rely on the visual capture of different types of click event.

To recreate *disable* the following preference:

Preferences > Keyboard > Behavior > Do not show Left Click, PrintScreen and other potentially "annoying" keys

I am running v4.66.0 (registered)

**Comment by marius-sucan** [comment]
Hello!

Thank you for contacting me. Apologies for the late reply, I do not check so often this web site. Clients usually contact me by email.

Please be more specific. I need to know if the following settings are on or off:
1. Typing mode [mixed or disabled]
2. Detect complex keyboard combinations.
3. Show mouse keys.
4. Show single keys.

Best regards, Marius.

**Comment by chrislockwood** [comment]
> Hello!
> 
> Thank you for contacting me. Apologies for the late reply, I do not check so often this web site. Clients usually contact me by email.

I have tried to reach out to you outside of Github, for this and other development suggestions, but regrettably no response.
> 
> Please be more specific. I need to know if the following settings are on or off:
> 
> 1. Typing mode [mixed or disabled]

Mixed (out of the box)
> 2. Detect complex keyboard combinations.

Disabled (out of the box)
> 3. Show mouse keys.

? (I'm not sure where this setting is)
> 4. Show single keys.

Enabled (out of the box)
> 
> Best regards, Marius.

This issue is easily reproduced by selecting "_Restore Defaults_" and then by changing the setting first reported "_Do not show Left Click, PrintScreen and other potentially "annoying" keys_".

![KeyPressOSD-Double-Click](https://user-images.githubusercontent.com/1902573/104813864-bcc36400-5803-11eb-827a-c984faef91c7.gif)

**Comment by marius-sucan** [comment]
Hello!

I was able to reproduce the bug. Thank you . I will let you know here when the release will be available with this fix.

Please tell me where you attempted and failed to reach me. I am available through: Facebook,   my personal web site [contact page] and others... Even KeyPress OSD has a direct link to my email address on Gmail [at About]. I admit, i never check the spam folder on Gmail...

I am open to development ideas, please feel free to offer me your suggestions.

Best regards, Marius.

**Comment by chrislockwood** [comment]
> I was able to reproduce the bug. Thank you . I will let you know here when the release will be available with this fix.

Good man, thanks for this.

> Please tell me where you attempted and failed to reach me. I am available through: Facebook, my personal web site [contact page] and others... Even KeyPress OSD has a direct link to my email address on Gmail [at About]. I admit, i never check the spam folder on Gmail...

I tried via your two website links, which funnel attempts to contact via a "contact us" page (no email exposed).

> I am open to development ideas, please feel free to offer me your suggestions.

Great, I'll ping you a direct email once the above issue is resolved.  Thanks for your effort on this project, it really is invaluable :)

**Comment by marius-sucan** [comment]
The new KeyPress OSD version is ready and published on its official site: v4.66.1. Please let me know if you have any other suggestions or feedback.

Best regards, Marius.
