### ISSUE TITLE
Opacity background and text property

### ISSUE THREAD

**Issue by vnvyvu** [marius-sucan/KeyPress-OSD#16]
it would be great if i could
i'm using free version

**Comment by marius-sucan** [comment]
Please elaborate. I don't understand exactly what you'd want.

**Comment by vnvyvu** [comment]
@marius-sucan 
https://en.wikipedia.org/wiki/RGBA_color_model
![image](https://user-images.githubusercontent.com/22812601/100458117-d266b800-30f5-11eb-8382-d5cd8491699e.png)
currently i can customize only 3 attributes: R(red), G(green), B(blue). Can you add Alpha property? It determines transparency of the pixel
maybe:
https://www.autohotkey.com/boards/viewtopic.php?t=9923

**Comment by marius-sucan** [comment]
The freeware edition of KeyPress OSD does not have yet this option, to set the opacity of the OSD. Future versions will have it.

Best regards, Marius.

**Comment by TheBitcoinBaron** [comment]
Is this added yet?

**Comment by marius-sucan** [comment]
No. It will not be added soon. Try the commercial edition. If you like it, buy it.
