### ISSUE TITLE
coordinates=0

### ISSUE THREAD

**Issue by vnvyvu** [marius-sucan/KeyPress-OSD#17]
![image](https://user-images.githubusercontent.com/22812601/100460567-f926ed80-30f9-11eb-9b63-28a3c3fdd231.png)
that value is always set to 1 when I set it to 0

![image](https://user-images.githubusercontent.com/22812601/100460939-a26de380-30fa-11eb-971b-ced08cdf0a00.png)

**Comment by marius-sucan** [comment]
That is a future , not a bug :-).
