### ISSUE TITLE
"Allow drag to reposition" setting no longer retained.

### ISSUE THREAD

**Issue by chrislockwood** [marius-sucan/KeyPress-OSD#18]
Since upgrading to OSD keypress v4.66.1 it is longer possible to enable the dragging of the OSD window, this setting is not retained after selecting apply.  

![KeyPressOSD-Drag-OSD](https://user-images.githubusercontent.com/1902573/105481189-9fc4e000-5c9e-11eb-8706-ba2d0cd0c3a9.gif)

**Comment by marius-sucan** [comment]
Bug confirmed. Other bugs were identified, a new version will be issued soon.

Please do not hesitate if you have any other bug or suggestion to report.

Thank you very much .

**Comment by chrislockwood** [comment]
Manually modifying the ini file (_DragOSDmode_) has no affect, and is overwritten following subsequent setting changes made within the app.

**Comment by marius-sucan** [comment]
The bug has been fixed.

Work-around until i release the version: deactivate attach toolbar to OSD. I had a silly mistake... ;[.

Best regards, Marius.

**Comment by marius-sucan** [comment]
The new version has been released.

Please do not hesitate to report bugs or if you have suggestions.

Best regards, Marius.

**Comment by chrislockwood** [comment]
Both your workaround and the subsequent release worked perfectly, many thanks for the rapid feedback & resolution!
