### ISSUE TITLE
Make the OSD not disappear

### ISSUE THREAD

**Issue by andreluizgollo** [marius-sucan/KeyPress-OSD#19]
Hi there!
I've got no idea if this is the right place to ask this. But I'm having trouble finding a way for the onscreen display to never disappear, even after several seconds from the last key pressed. Is there a way for doing this?

Thank you very much!

**Comment by marius-sucan** [comment]
Hello!

Set OSD display times at the maximum allowed values, at preferences. 

If that's not enough, let me know. 

Best regards, Marius.

**Comment by andreluizgollo** [comment]
Oh, it was so right in front of me. No idea how I missed it.
Thanks for the reply! Great tool, by the way.

**Comment by marius-sucan** [comment]
Thank you.

You can also try the commercial edition. It has lots of improvements.

Best regards, Marius.
