### ISSUE TITLE
[Feature request] Disable Shift+key, if showing single keys are disabled

### ISSUE THREAD

**Issue by Kristinita** [marius-sucan/KeyPress-OSD#2]
### 1. Request

**If** `Show single keys` disabled in settings:

    It would be nice, if <kbd>Shift+key</kbd> will disable.

`key` — any key in keyboard.

### 2. Justification

<kbd>Shift+key</kbd> function:

1. Input capital letter,
1. Input another symbol.

**If** I disable `Show single keys`, I want, that displayed only hotkeys, but not text, that I input.

### 3. Actual behavior

![Actual](https://imgur.com/8ysEMQp.png)

### 4. Expected behavior

No OSD in example above.

Thanks.

**Comment by marius-sucan** [comment]
I do not want to make it too "bloated" with tons of options. I thought of adding many more options, but... I refrained from this, because it gets bloated.

As I previously noted, to your Feature request: I will likely add Center alignment, along with Right and Left [which are implemented already].
