### ISSUE TITLE
"Shrink text to fit" changes font family and weight

### ISSUE THREAD

**Issue by CerVieel** [marius-sucan/KeyPress-OSD#20]
Enabling the setting "**Shrink text to Fit**" (Preferences > OSD appearance) causes KeyPress OSD to ignore the font family settings. The font weight is also being increased no matter the shrink setting, one weight if disabled or full-on to bold if enabled.

I located the lines responsible and while I'm not sure if my quick fix breaks something else it's a starting point, I guess.

In the **CreateOSDGUI()** function:
```
(...)
    If (ShowPreview=0 || PrefOpen=0)
       ; Gui, OSD: Font, c%OSDtextColor% Bold, %FontName%, -wrap  ; FIX: Remove "Bold"
       Gui, OSD: Font, c%OSDtextColor%, %FontName%, -wrap
    Else
       Gui, OSD: Font, c%OSDtextColor%, -wrap
(...)
If (PrefOpen!=1)
    {
       FontSizeHorizProgress := (FontSize<60) ? Round(FontSize/5.5) : Round(FontSize/10)
       If (FontSize<20)
          FontSizeHorizProgress := Round(FontSize/2.9)
       If (FontSize>130)
          FontSizeHorizProgress := Round(FontSize/15)
       If (FontSizeHorizProgress<9)
          FontSizeHorizProgress := 8
       ; Gui, OSD: Font, s%FontSizeHorizProgress%, Arial  ; FIX: Switch "Arial" to user-set FontName
       Gui, OSD: Font, s%FontSizeHorizProgress%, %FontName%
       Gui, OSD: Add, Text, x+0 -wrap vTextNavPrev, ----------------------
       GuiControl, OSD: Move, TextNavPrev, h%smallLEDheight%
       GuiControl, OSD:, TextNavPrev, 
    }
```
There's a third Font definition using Arial in this function, but I didn't touch it since changing these lines already solved the issue.

I hope this helps, and thanks for the fantastic app!

**Comment by marius-sucan** [comment]
Hello!

Thank you for the report and fix suggestions.

The line containing Arial you modified pertains to the horizontal line that indicates how much of the text you typed is visible in the OSD. The change of the font breaks that small "horizontal progress bar" which relies on some ASCII characters found in Arial. 

The other line, with bold, is for those small LEDs in the top, left corner that light up when you press modifiers or have num lock or scroll lock activated. Shouldn't break anything, just change their look a little. 

I'll have to look into it to confirm the bug you mentioned.

I'll come back with a reply  later today. Now I'm going to bed. ^_^

Thanks again. 

Best regards, Marius.

**Comment by CerVieel** [comment]
Thanks for looking into it! The fact that altering these lines fixed the issue didn't make sense to me either, but if it works who am I to complain? 

I realize that my bug report was super sloppy, so additional info:
- The bug happens in both the .ahk and the compiled versions, download from the link in this repo home.
- OS: Windows 8.1 x64 edition
- AHK: 1.1.33.09 (previously AutoHotkey_L, I had to edit that line in the script version of KeyPress OSD)

I can provide screenshots or videos if needed.

**Comment by marius-sucan** [comment]
Helllo!

The bug is indeed present in the free edition of KeyPress OSD . I confirm it.

The bold issue: in the old free edition version, there is no option to set or unset bold. It is always assumed bold. At some point , the option was implemented, and is present in the latest KeyPress OSD version. And the shrink option does not break the font family.

At a quick glance, I am unable to understand why the font is reset for the edit. The text control for the horizontal «progress»  thingy is added after the edit control. So I do not know why it gets finnicky.


Please try... Undo the changes you made and before [line 3214]:
    Gui, OSD: Show, NoActivate Hide x%GuiX% y%GuiY%, KeyPressOSDwin  ; required for initialization when Drag2Move is active

Add this function call:
UpdateFntNow()

Let me know if it works.

Best regards, Marius.
