### ISSUE TITLE
Error message "continuable expection_acess_violation"

### ISSUE THREAD

**Issue by santiyounger** [marius-sucan/KeyPress-OSD#21]
Hey, I'm in the trial, and I'd love to be able to fully test this app and then buy it, however I keep getting this message, whenever I try to use the app.

The LineFile is in an asian language, so I can't even understand what's going on
![image](https://user-images.githubusercontent.com/51902730/135175765-b09e9893-77e0-46bf-ad12-277266d9c261.png)

If I click on Yes, the app doesn't fully work, and of course if I press No or Cancel the app shuts down.

would appreciate any help with this thanks!

**Comment by marius-sucan** [comment]
You need to save all the ahk files in utf-8 with bom.

**Comment by santiyounger** [comment]
thanks for the fast reply. I actually decided to buy it through gumroad, and that download link worked great!

The activation key arrives to the email right? since it's still on trial for now!

Thanks for the great app, keep up the awesome work!

**Comment by santiyounger** [comment]
quick update:
first thanks a lot, I already got my activation code, really appreciate how quick it was.

now that I have the full version, I got the ERROR message again, however this time clicking "Yes" seemed to work.

just to avoid this message in the future can you please help me by explaining how to achieve this:

> You need to save all the ahk files in utf-8 with bom.

where can I find these autohotkey files? unfortunately I'm not familiar with the terms utf-8 nor bom.

would really appreciate it if you can give me a hand just to avoid issues.

Also should I move the downloaded folder to "Program Files" or does it not matter where it is located

Thanks

**Comment by marius-sucan** [comment]
Good morning !

The AHK files are the source code of the application . The said source code is available here, on Github, but it is only for the free/old version. It would defeat the purpose to have the source files easily accessible in the commercial edition.

In advanced text editors, when you open files, you can choose the encoding format for text files upon save. UTF-8 with BOM is a kind of encoding format suitable.

If you experience issues with the KeyPress OSD commercial edition, please let me know .

KeyPress OSD is portable, it needs no installation. You can place it anywhere, as long as it has file access in the folder where it is located.

Best regards, Marius.
