### ISSUE TITLE
Is it possible to display only specific keys/combinations?

### ISSUE THREAD

**Issue by tamas-ferenci** [marius-sucan/KeyPress-OSD#24]
For instance, if I only want `Ctrl + Enter` to be displayed (and nothing else). I unfortunately couldn't find such option.

**Comment by marius-sucan** [comment]
Hello!

There's currently no such option. Sorry...

Best regards, Marius.

**Comment by tamas-ferenci** [comment]
Thank you very much, I appreciate your rapid answer! Then take it as a feature suggestion, if your time permits, and consider it useful...

**Comment by marius-sucan** [comment]
Thank you. I'll keep both issues on github you created as open for future reference, for when I'll return this project. Currently I'm very much focused on Quick Picto Viewer.

Best regards, Marius.

**Comment by tamas-ferenci** [comment]
Thank you!

**Comment by marius-sucan** [comment]
It is now possible to do this in v4.68.0. But it is only in the commercial version. I will close this issue. Thank you again for the suggestions.
