### ISSUE TITLE
Multiple monitors change OSD position A B

### ISSUE THREAD

**Issue by DigitalArtz** [marius-sucan/KeyPress-OSD#25]
Here's a strange issue/use case.

The KeyPress OSD is by default displayed on the primary screen (which is cool) and I'd want to be able to switch it to a secondary screen using the A/B positions. The problem is I can't set a negative value for the positions (secondary monitor is to the left and set as extended display if that's important).

This issue can be bypassed if I use the Drag OSD option, but it only lasts until I close the script - the Drag OSD option does set a negative value for the A/B position as it works as I would expect it to and it is also reflected in the OSD appearance. However, the values aren't saved.

**Comment by marius-sucan** [comment]
This should now be fixed. Thank you .
