### ISSUE TITLE
Localization for other Languages avaliable?

### ISSUE THREAD

**Issue by Beowolve** [marius-sucan/KeyPress-OSD#27]
Is there support to display the pressed keys in a different language (german)?
If not, where would I need to change the display text without breaking the script? (no ahk experience)

**Comment by marius-sucan** [comment]
Hello!

The commercial edition, which has many improvements and fixes, already has support to display the keystrokes in French, German, Russian or Spanish.

Please consider buying it. Thank you for your interest.

Best regards, Marius.
