### ISSUE TITLE
Allow global keyboard shortcuts to pass through to another application

### ISSUE THREAD

**Issue by i-give-up** [marius-sucan/KeyPress-OSD#3]
Environment: Windows 8.1, Keypress OSD v4.28.6

I'm trying to use KeyPress OSD along with [OBS Studio](https://obsproject.com) so that I can show typed keys and mouse clicks when recording my screen.

In both KeyPress OSD and OBS Studio, I have set Ctrl + F12 as the key to toggle activate/deactivate.

The issue is that when I press Ctrl + F12 to deactivate both KeyPress OSD and OBS Studio, KeyPress OSD deactivates just fine but OBS Studio doesn't (i.e. it continues to record). What I'm guessing is that KeyPress OSD intercepts the keys but doesn't pass it through so OBS Studio never receives/detects the keys.

As a sidenote, I've used OBS Studio together with a modified version of [ripple AHK script](https://autohotkey.com/boards/viewtopic.php?t=8963) before with a shared hotkey Ctrl + F12 so I know it's possible to toggle both at the same time. The modification involves setting Ctrl + F12 as the hotkey to activate/deactivate the ripple AHK script.

**Comment by marius-sucan** [comment]
Hello!

In the new version of KeyPress OSD I added an option: Allow other apps to use the same shortcuts.

Please confirm it works.

Best regards, Marius.

**Comment by i-give-up** [comment]
Works great. Thanks.
