### ISSUE TITLE
Ability to make text size smaller

### ISSUE THREAD

**Issue by hced** [marius-sucan/KeyPress-OSD#31]
For me, the size is too large. It says in the features list `Automatic resizing of OSD/HUD or fixed size` but I couldn't find out where this is adjusted.

**Comment by marius-sucan** [comment]
Hello!
Hello!

Go to KeyPress OSD / System Tray Icon / Preferences / OSD appearances. In that panel you can adjust font size and OSD dimensions and behaviour.

Best regards, Marius.

**Comment by hced** [comment]
Fantastic! Thanks. (I was looking for this preference in the Settings window.)
