### ISSUE TITLE
pb with Shift+Winkey+S (Trial pro version))

### ISSUE THREAD

**Issue by monkeymoong** [marius-sucan/KeyPress-OSD#32]
Hello,
i'm just trying the trial pro version
i can't manage to display the "S" of "Shift+Winkey+S" (Windows capture)
i could do that with the free version
is there something to do ?
thanks for reply

**Comment by marius-sucan** [comment]
Hello!

Try to deactivate the option, hide annoying keys found in the keyboard options panel. 

If it doesn't work, let me know. 

Best regards, Marius.

**Comment by monkeymoong** [comment]
if it's the option :
"Do not show Left Click. Print Screen and other potentially "annoying" keys"
it was deactivate. I try to activate and deactivate it but it's the same result

**Comment by marius-sucan** [comment]
Yes, I agree . Problem was identified and fixed.

Please redownload the trial and it will work when it is deativated. 

Thank you for reporting the problem. I hope you'll buy it ;-). I would appreciate it a lot.

Best regards, Marius.
