### ISSUE TITLE
can't disable AltGr

### ISSUE THREAD

**Issue by monkeymoong** [marius-sucan/KeyPress-OSD#35]
Hello 
perhaps it's a normal thing but
when i try to disable AltGr it always display Ctrl ?
Thanks for reply

**Comment by marius-sucan** [comment]
There is no option for disabling AltGr.

**Comment by marius-sucan** [comment]
I have identified the bug. It'll be fixed.

**Comment by marius-sucan** [comment]
Bug fixed in v4.68.9.1.
