### ISSUE TITLE
a small error in the text ?

### ISSUE THREAD

**Issue by monkeymoong** [marius-sucan/KeyPress-OSD#36]
in the Window "Rename keys:..."
"custo_m_ names" in the tab
;-)

**Comment by marius-sucan** [comment]
Thank you.

Please buy the commercial version. Your trial version should have expired.

**Comment by monkeymoong** [comment]
I'm sorry, i understand,
at the moment i just check the application in a VM
i don't really use it, because i have no such needs at this time
I'm just curious, and i like to be aware of the new ideas and softwares
I wish you will manage to make known your soft and of course to sell it...
so i hope you won't blame me to much...
;-)

**Comment by marius-sucan** [comment]
No blame from me, hehe.

Thank you for testing KeyPress OSD and reporting me bugs. I am working on the «disable AltGr» bug. It is almost fixed.
