### ISSUE TITLE
The pay version can avoid showing the clipboard on the screen?

### ISSUE THREAD

**Issue by joaoruntime** [marius-sucan/KeyPress-OSD#37]
When I use ctrl + v, the clipboard is shown on the screen, and I don't want that to happen, I want that show ctrl + v in the screen not the clipboard

**Comment by marius-sucan** [comment]
Go to Preferences > Keyboard > Clipboard tab. Deactivate «show clipboard changes».

Another option is:
Go to Quick start presets and select Screen cast. This will deactivate the typing mode.

Best regards, Marius.

**Comment by joaoruntime** [comment]
It works, but I like the Typemode; maybe consider adding an option to disable clipboard paste text in the Typemode settings

**Comment by marius-sucan** [comment]
Thank you . I will add this option.

**Comment by marius-sucan** [comment]
The option is now available, in v4.69.1, released today.
