### ISSUE TITLE
Can I set the app to restart (refresh) display and not append text?

### ISSUE THREAD

**Issue by Bemo3** [marius-sucan/KeyPress-OSD#38]
Thank you for a great app :)

However, I can't find any setting that lets me restart (refresh) text entry after a predetermined delay (without using a shortcut), it continually appends to the previous displayed entry. Did I miss something? Can this be done?

**Comment by marius-sucan** [comment]
Please deactivate text mode from preferences.

**Comment by Bemo3** [comment]
Marius,

Thank you for your reply. Sadly, when you "disable main typing mode", this also defeats the ability to display an string input that may be more than one or two characters. Disabling also forces commas in between each character; this is not ideal in my case. Furthermore, and more importantly for me, disabling writing mode also disables seeing native symbol characters (like @ # $ etc). i.e. I prefer having # represented as that symbol and not as Shift+3.

So, what I really was asking for was to be able to simply refresh the input display (after a set fade out time) so it does not append to a previous string. Thus, a displayed input string of "abc@def456" could fade out after a set time and allow me to restart a new string without appending to the previous.

I hope you will consider adding this behaviour to your application.

Many thanks, again, for your reply.

**Comment by marius-sucan** [comment]
Please go to the typing mode options...

In the first tab, general, change "time to resume typing mode". Maybe it's what you need.

Best regards, Marius.

**Comment by Bemo3** [comment]
Yes, Marius, I've tried this many times... At one point, it seemed to work, but then it wasn't.

What I've observed is that you can input up to 3 characters, let the display time out, and then enter new characters that won't append. Great. However, as soon as you enter more than 3 characters, the display appends and will never restart unless you press the proper option switch (return, for example). Maybe this is a bug?

Also, (as shown in the gif), even though I entered a value of 1 in the OSD time to resume, and time display entries, it won't keep it. Instead, it defaults to a minimum value of 3.

Again, thank you for following up on this.

**Comment by marius-sucan** [comment]
Hello!

The typing mode behaviour was meticulously developed such that it retains the text. I use typing mode on a daily basis, constantly for years. This is why I developed KeyPress OSD in the first place. Internally, there are various conditions that define whether the text line is erased or maintained. These emerged gradually by observing my needs over months and years of usage.

My initial logic was that the «return to type» delay must be longer than display time by one second. In recent versions I reduced the minimum allowed values to 1 second for both.

Based on your feedback, I updated the code such that when return time to typing is lower or equal to display time, all other clauses that prolong the text to stay on screen are ignored and the text line is renewed. Please try it and let me know if it is behaving how you need it to.

Download link:
https://files.sucan.ro/marius/blog/ahk-scripts/keypress-osd-trial.zip

Best regards, Marius.

**Comment by Bemo3** [comment]
Hello Marius :)

This is great work, thank you! I tested this and all seems fine. However, if settings are at 1 sec for display and resume time, the behaviour is such that a one or two character entry actually prolongs the display time. Entry of three characters or more respects the value accordingly. I have set my values to 2 sec each and all behaves as I expect it to. I think this is a great compromise.

You are most kind to add these changes. I believe everyone can benefit as your application can now behave like all the other keypress display apps out there, but in my opinion, does a better job...especially given the special instructions you've embedded. Congratulations on this!

Is there a toggle switch to show/hide the text caret to the right of the character?

Thank you, once again!

**Comment by marius-sucan** [comment]
Thank you! I am glad it is now better suited for your needs.

There's currently no option to hide the caret. It's typing mode...

Should I add an option for this? 

How about to limit the text length? Eg.  two characters. 

Best regards, Marius.

**Comment by Bemo3** [comment]
Yes, I think adding the ability to hide the caret would suit some of your users (and me) who simply want to display key presses for screen casting. I hope to use your app to display my key presses for a special font in another application, to clearly display what keys are being pressed to produce the font's resulting character substitutions. Showing the caret might be a visual obstacle.

As for limiting text length to two characters...I don't know why a user might need this. Perhaps you know better in this regard. I can see how powerful your application is. I am only using 10-20% of its potential. But it's all I need at this time :)

**Comment by marius-sucan** [comment]
Hello, again!

Based on your words, I conclude I should add in the Typing mode settings panel an option that reads: Screencast mode . When activated, the string is limited to one letter and no visible caret. Would this be a good idea ? I understand some people need the typing mode behaviour of showing keys such as A, a, 2, @, et cetera , but for screen cast one never needs  more than one letter/symbol at a time - this is why i suggested the option for limiting the number of characters to eg, 1 or 2, 3, ... Please let me know your thoughts on this.

The settings are all stored in the INI file[s]. No options to save custom presets. I might add this in the future.

The features I use on daily basis in KeyPress OSD are: typing mixed-mode, auto-expand abbreviations/shorthands when I type, clipboard history, keyboard sound beeps, and its mouse keys. All of the other features are too niche for me ^_^ .

Best regards, Marius. 




Best regards, Marius.

**Comment by marius-sucan** [comment]
Hello, again!

Based on the feedback you provided, I released a new version of KeyPress OSD :

v4.69.2 (2023-12-20) - commercial release
 - [new] option to show characters affected by Shift even in screen cast mode, eg., 'Shift + 2' will show as '@'; this option is at Keyboard Panel > Behaviour tab
 - [new] option to limit typing mode to a user specified number of characters ; this option is at Typing mode panel > First tab
 - [new] option to hide the text caret in the OSD when typing mode is activated [Typing mode panel > First tab] 
 - other minor improvements

Please give it a try, let me know how it is.

Based on your explanations, I would deactivate typing mode and activate the new option from Keyboard.

Best regards, Marius.

**Comment by Bemo3** [comment]
Hello Marius,

Thank you for these changes!

I have downloaded the portable zip file (although it's still labeled as 4.69.1). I think my trial for this software is over. But more importantly, when I try to extract the files, I get a severe virus message and I can't get past it. Can you please verify?

![virus issues](https://github.com/marius-sucan/KeyPress-OSD/assets/152804137/f526ed88-ea76-4424-bbf1-8ca124ebd9c5)

**Comment by marius-sucan** [comment]
There are two downloads available... just because of the false virus warnings ... ;😔  Try both, perhaps one of them works without warnings.

I am aware of this problem. I even wrote about it on the site.

It is because it is based on AHK.

Yes, I forgot to update the site. I will update it now.

Please let me know how you find the new version once you tested it.

Best regards, Marius.

**Comment by Bemo3** [comment]
Hello again Marius,

I'm happy to report that all is working perfectly. You've now made this special application much more complete. In my opinion, this will easily compete with everything else that's out there...Windows or MacOS.
Congratulations!

P.S. Perhaps for a future update, just for the sake of finesse, you might consider adding a fade-out time to the display. However, this is certainly not crucial :)

Many, many thanks on a job well done!

**Comment by marius-sucan** [comment]
Thank you very much ! 👍 

Glad to hear you like the new version.
