### ISSUE TITLE
Error: CONTINUABLE EXCEPTION_ACCESS_VIOLATION

### ISSUE THREAD

**Issue by vavavr00m** [marius-sucan/KeyPress-OSD#39]
After registering, I got this error. I'm on W11 23H2 if that helps. Pressing Yes will stop it from displaying OSD and then relaunching doesn't bring up any window or tray icon. Had to kill the process for it to launch again.

![image](https://github.com/user-attachments/assets/7ad5f618-cf27-4170-9a36-f9e80a91d709)

**Comment by marius-sucan** [comment]
I am sorry about it... Please provide more information. 

Does it crash every time it starts?

**Comment by marius-sucan** [comment]
I can't think of something in particular.
. If it happens again, try to break it again and take note on what you do, or the contexts it happens. And after, write me back with the observations.

Do you use windows customization apps? Based on the screenshot, it seems like you do. If yes, then it's possible one of those apps interfered with KeyPress OSD.

Best regards, Marius.
