### ISSUE TITLE
[Feature Request] option to change opacity of the background

### ISSUE THREAD

**Issue by AlexSHoffman** [marius-sucan/KeyPress-OSD#7]
It would be nice if you could change the opacity of the background (Appearance > Style and colors)

P.S, good job mate, thank you for creating this script!

**Comment by marius-sucan** [comment]
Hello!

Thank you !

Changing the opacity leads to flickering. The whole window would flicker... Do you deem this as something important ?

Best regards, Marius.

**Comment by AlexSHoffman** [comment]
@marius-sucan oh okay, well, it's not that big of a deal, I suppose the case is closed then :)
Cheers mate
