### ISSUE TITLE
Right Alt is displayed as AltGr

### ISSUE THREAD

**Issue by Kotsuha** [marius-sucan/KeyPress-OSD#8]
As title. Right Alt is displayed as AltGr. Right Control is alright though.

![untitled](https://user-images.githubusercontent.com/10438710/39968571-c6d96b3e-5701-11e8-9733-bdedfcc6f0b1.png)

**Comment by marius-sucan** [comment]
Yes, that is correct. It is not an issue.

Left Alt = Alt; Right Alt = AltGr, this is the one which is used to type foreign/regional characters on some keyboards .

**Comment by Kotsuha** [comment]
Didn't know that. Okay.
