### ISSUE TITLE
Trojan:Win32/Zpevdo.A inside 

### ISSUE THREAD

**Issue by dmi3mis** [marius-sucan/KeyPress-OSD#9]
My Windows 10 antivirus found Trojan:Win32/Zpevdo.A inside your exe file.
Can you explain this?

**Comment by marius-sucan** [comment]
Hello!

I use Windows 10. I do not have this issue. Please give me more details. Which EXE?

Best regards, Marius.

**Comment by dmi3mis** [comment]
Trojan:Win32/Zpevdo.A found in x64 version of  keypress-osd.exe
I use Windows 10 1803 with updated Windows defender.
Here is a screenshot. (Sorry for not english interface, but i think you understand most of all.)
![screenshot_106](https://user-images.githubusercontent.com/11094711/41828665-d178deb4-7860-11e8-8dc4-65d7bdd2d04c.png)

https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3aWin32%2fZpevdo.A&threatid=2147727143

Here is a report of virustotal
https://www.virustotal.com/ru/file/c8cc2257d7da654819e611139f4076d6b3f658338940b194a3852cee4d5bf651/analysis/
https://www.virustotal.com/ru/file/ba876d0704f4a0c30255203d87a55fd4d35d2434b25ca956f1a330d10718c43c/analysis/1529896465/

I think its a false positive. And yes, false positive is about AutoHotkey_H inside your program.

Can i have a exe file without a bitcoin miner please? :)

**Comment by marius-sucan** [comment]
Hello!

Thank you very much for your detailed report.

How can I solve this issue? Do you have any suggestions?

I used the AHK-H compiler... I do not know how to fix this...

Best regards, Marius.

**Comment by dmi3mis** [comment]
ok

**Comment by marius-sucan** [comment]
Update.

Problem solved. I reported the file to Microsoft and now AHK_H x32 is no longer detected as a virus. 

Best regards, Marius.
